# Generated by Django 2.1.4 on 2021-08-16 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='item_quan',
            field=models.IntegerField(default=datetime.datetime(2021, 8, 16, 12, 36, 43, 42367, tzinfo=utc), max_length=3),
            preserve_default=False,
        ),
    ]
