# Generated by Django 2.1.4 on 2021-08-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_grocery_item_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='username',
        ),
        migrations.DeleteModel(
            name='grocery',
        ),
    ]
