# Generated by Django 2.1.4 on 2021-08-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_grocery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grocery',
            new_name='grocery1',
        ),
    ]
