# Generated by Django 2.1.4 on 2021-08-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20210816_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='usergr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_quan', models.IntegerField(max_length=3)),
                ('item_status', models.CharField(max_length=50)),
                ('item_date', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.userTable')),
            ],
        ),
    ]
